"""Thresholds and weights for Stage 5.5 deterministic proposal generation."""

from __future__ import annotations

DEFAULT_GENERATOR_VERSION = "proposal_gen.v1"

DUPLICATE_THRESHOLD = 0.88
MERGE_SCORE_MIN = 0.72
MERGE_SCORE_MAX_EXCLUSIVE = 0.88
CANONICAL_THRESHOLD = 0.75

TOKEN_OVERLAP_PRUNE_MIN = 0.15

# Duplicate candidate weights (doc §10.3)
W_DUP_TEXT = 0.45
W_DUP_SAME_CONCEPT = 0.15
W_DUP_SAME_SUBCONCEPT = 0.10
W_DUP_SHARED_EVIDENCE = 0.10
W_DUP_SHARED_SOURCE_EVENT = 0.10
W_DUP_NON_GOLD_PAIR = 0.05
PENALTY_SAME_LESSON = -0.05

# Merge candidate weights
W_MERGE_TEXT = 0.35
W_MERGE_SAME_CONCEPT = 0.20
W_MERGE_SAME_SUBCONCEPT = 0.10
W_MERGE_CONDITION_COMPAT = 0.10
W_MERGE_SHARED_EVIDENCE = 0.10
W_MERGE_ONE_IN_ACTIVE_FAMILY = 0.10
W_MERGE_BOTH_PROVENANCE = 0.05

# Canonical family candidate
W_CANON_TEXT = 0.40
W_CANON_CONCEPT = 0.20
W_CANON_SUBCONCEPT = 0.10
W_CANON_MEMBER_OVERLAP = 0.20
W_CANON_ACTIVE = 0.10

# Queue priority bonuses (doc §15)
Q_BONUS_UNRESOLVED = 0.10
Q_BONUS_SOURCE_NOT_GOLD = 0.05
Q_BONUS_RELATED_ACTIVE_FAMILY = 0.05
