# Refresh Stage 5.1 adjudication audit bundle and zip.
# Zip contains ONLY paths listed in $ArchiveRelativePaths (must match AUDIT_FILE_LIST.md).
# Run:  powershell -File audit/stage5-1-adjudication/package_bundle.ps1

param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
)

$ErrorActionPreference = "Stop"

# --- Authoritative archive manifest (keep in sync with AUDIT_FILE_LIST.md tree) ---
$ArchiveRelativePaths = @(
    "AUDIT_HANDOFF.md",
    "AUDIT_FILE_LIST.md",
    "AUDIT_VALIDATION_OUTPUT.txt",
    "POST_AUDIT_INTEGRITY_HANDOFF.md",
    "README.md",
    "package_bundle.ps1",
    "pipeline/adjudication/__init__.py",
    "pipeline/adjudication/bootstrap.py",
    "pipeline/adjudication/docs.md",
    "pipeline/adjudication/enums.py",
    "pipeline/adjudication/errors.py",
    "pipeline/adjudication/models.py",
    "pipeline/adjudication/policy.py",
    "pipeline/adjudication/repository.py",
    "pipeline/adjudication/resolver.py",
    "pipeline/adjudication/storage.py",
    "pipeline/adjudication/time_utils.py",
    "tests/test_adjudication_integrity.py",
    "tests/test_adjudication_models.py",
    "tests/test_adjudication_resolver.py",
    "tests/test_adjudication_restart.py",
    "tests/test_adjudication_storage.py"
)

$Bundle = Join-Path $RepoRoot "audit\stage5-1-adjudication"
$Archives = Join-Path $RepoRoot "audit\archives"
$ZipPath = Join-Path $Archives "stage5_1_adjudication_bundle.zip"
$SrcAdj = Join-Path $RepoRoot "pipeline\adjudication"
$DestAdj = Join-Path $Bundle "pipeline\adjudication"
$DestTests = Join-Path $Bundle "tests"

if (-not (Test-Path $SrcAdj)) { throw "Missing: $SrcAdj" }

New-Item -ItemType Directory -Force -Path $DestAdj | Out-Null
New-Item -ItemType Directory -Force -Path $DestTests | Out-Null
New-Item -ItemType Directory -Force -Path $Archives | Out-Null

function Remove-BundleBytecode {
    param([string]$Root)
    if (-not (Test-Path $Root)) { return }
    Get-ChildItem $Root -Recurse -Directory -Filter "__pycache__" -ErrorAction SilentlyContinue |
        ForEach-Object { Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue }
    Get-ChildItem $Root -Recurse -Filter "*.pyc" -ErrorAction SilentlyContinue |
        ForEach-Object { Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue }
}

# Wipe snapshot trees under bundle (pipeline/tests only)
if (Test-Path $DestAdj) {
    Get-ChildItem $DestAdj -Force | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
}
if (Test-Path $DestTests) {
    Get-ChildItem $DestTests -Force | Remove-Item -Force -ErrorAction SilentlyContinue
}

Copy-Item (Join-Path $SrcAdj "*.py") $DestAdj -Force
Copy-Item (Join-Path $SrcAdj "docs.md") $DestAdj -Force

Get-ChildItem (Join-Path $RepoRoot "tests") -Filter "test_adjudication_*.py" | ForEach-Object {
    Copy-Item $_.FullName $DestTests -Force
}

Remove-BundleBytecode $Bundle

# Validation log (pytest + compileall) — repo sources
$log = Join-Path $Bundle "AUDIT_VALIDATION_OUTPUT.txt"
$pytestTests = @(
    "tests/test_adjudication_models.py",
    "tests/test_adjudication_resolver.py",
    "tests/test_adjudication_storage.py",
    "tests/test_adjudication_restart.py",
    "tests/test_adjudication_integrity.py"
)
Push-Location $RepoRoot
try {
    @"
=== Stage 5.1 adjudication — validation (generated by package_bundle.ps1) ===
Repo: $RepoRoot
Time: $(Get-Date -Format o)

--- Command ---
python -m pytest $($pytestTests -join ' ') -v --tb=short

"@ | Set-Content -Path $log -Encoding utf8
    & python -m pytest @pytestTests -v --tb=short 2>&1 | Add-Content -Path $log -Encoding utf8
    $pytestExit = $LASTEXITCODE
    "`npytest exit code: $pytestExit`n" | Add-Content -Path $log -Encoding utf8
    "`n--- Command ---`npython -m compileall -q pipeline/adjudication`n" | Add-Content -Path $log -Encoding utf8
    & python -m compileall -q pipeline/adjudication 2>&1 | Add-Content -Path $log -Encoding utf8
    if ($LASTEXITCODE -eq 0) { "`ncompileall: PASS" | Add-Content -Path $log -Encoding utf8 }
    else { "`ncompileall: FAIL (exit $LASTEXITCODE)" | Add-Content -Path $log -Encoding utf8 }
    @"

--- Notes ---
- ruff / mypy: not configured in project pyproject.toml; not run here.
- Zip: built from explicit manifest only (see `$ArchiveRelativePaths` in package_bundle.ps1); must match AUDIT_FILE_LIST.md.
"@ | Add-Content -Path $log -Encoding utf8
}
finally {
    Pop-Location
}

Remove-BundleBytecode $Bundle

# --- Staging: only manifest files (clean archive, no stray bundle files) ---
$StageParent = Join-Path $env:TEMP ("stage5_1_audit_zip_" + [Guid]::NewGuid().ToString("n"))
$Stage = Join-Path $StageParent "root"
New-Item -ItemType Directory -Force -Path $Stage | Out-Null
try {
    foreach ($rel in $ArchiveRelativePaths) {
        $relNorm = $rel -replace "/", [IO.Path]::DirectorySeparatorChar
        $srcPath = Join-Path $Bundle $relNorm
        if (-not (Test-Path $srcPath)) {
            throw "Archive manifest references missing file: $rel (expected at $srcPath)"
        }
        $destPath = Join-Path $Stage $relNorm
        $destDir = Split-Path $destPath -Parent
        if (-not (Test-Path $destDir)) {
            New-Item -ItemType Directory -Force -Path $destDir | Out-Null
        }
        Copy-Item $srcPath $destPath -Force
    }

    Remove-BundleBytecode $Stage

    if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }
    Compress-Archive -Path (Join-Path $Stage "*") -DestinationPath $ZipPath -Force

    # Verify zip: exact file set, no bytecode
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $zip = [System.IO.Compression.ZipFile]::OpenRead($ZipPath)
    try {
        $actual = New-Object "System.Collections.Generic.HashSet[string]"
        foreach ($e in $zip.Entries) {
            $name = $e.FullName.Replace("\", "/")
            if ($name.EndsWith("/")) { continue }
            if ($name -match "__pycache__|\.pyc($|/)") {
                throw "Zip contains forbidden path: $name"
            }
            [void]$actual.Add($name)
        }
        $expected = New-Object "System.Collections.Generic.HashSet[string]"
        foreach ($r in $ArchiveRelativePaths) { [void]$expected.Add($r) }

        if ($actual.Count -ne $expected.Count) {
            throw "Zip entry count $($actual.Count) != manifest count $($expected.Count)"
        }
        foreach ($r in $ArchiveRelativePaths) {
            if (-not $actual.Contains($r)) {
                throw "Zip missing manifest path: $r"
            }
        }
        foreach ($a in $actual) {
            if (-not $expected.Contains($a)) {
                throw "Zip contains unexpected path (not in manifest): $a"
            }
        }
    }
    finally {
        $zip.Dispose()
    }
}
finally {
    if (Test-Path $StageParent) {
        Remove-Item $StageParent -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Write-Host "Wrote $ZipPath (manifest: $($ArchiveRelativePaths.Count) files, verified)"
